Enhancements to docker sync. Include better error handling and an option to run jobs in parallel.

diff --git a/docker-registry-sync b/docker-registry-sync
--- a/docker-registry-sync
+++ b/docker-registry-sync
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+error_out() {
+  echo "ERROR: ${1}"
+  echo "ERROR: See ${LOGFILE} for more details."
+  exit 1
+}
+
+do_sync() {
+  image_url="${registry_url}/${image}"
+
+  echo "(1/3) Pulling Image ${image_url}..." | tee ${LOGFILE}
+  docker pull ${image_url} &>>${LOGFILE} || error_out "Failed to PULL image: docker pull ${image_url}"
+  image_id=`docker images | awk "/${image_url//\//\\/}/"' {print $3}'`
+
+  echo "(2/3) Tagging Image ${image_id}|${image}..." | tee ${LOGFILE}
+  docker tag -f ${image_id} ${local_registry_url}/${image} &>>${LOGFILE} || error_out "Failed to tag image: docker tag -f ${image_id} ${local_registry_url}/${image}"
+
+  echo "(3/3) Pushing Tag ${local_registry_url}/${image}..." | tee ${LOGFILE}
+  docker push ${local_registry_url}/${image} &>>${LOGFILE} || error_out "Failed to push image: docker push ${local_registry_url}/${image}"
+  echo "Completed Push of image: ${image}"
+}
+
 usage() {
   echo "$0:
 
@@ -12,11 +33,13 @@ Options:
   --from <public-registry-hostname> : Name of the public registry you wish to PULL images from (i.e. docker.io, registry.access.redhat.com)
   --local <local-registry>          : Location of private registry you wish to PUSH images to (i.e. localhost:5000, registry.mydomain.com)
   --file <image-file>               : Text file containing a list of image names (one image name per line)
+  --parallel                        : Run multiple syncs in parallel, for faster runs on beefy servers
 "
 }
 
 LOGFILE=~/docker_image_sync.log
 touch ${LOGFILE}
+parallel=false
 
 for i in "$@"
 do
@@ -29,6 +52,9 @@ do
       shift;;
     --local=*)
       local_registry_url="${i#*=}"
+      shift;;
+    --parallel)
+      parallel=true;
       shift;;
     *)
       echo "Invalid Option: ${i%=*}"
@@ -48,15 +74,14 @@ done
 images=`cat ${file_path}`
 
 for image in $images; do
-(
-  image_url="${registry_url}/${image}"
-  docker pull ${image_url} &>${LOGFILE}
-  image_id=`docker images | awk "/${image_url//\//\\/}/"' {print $3}'`
-  docker tag ${image_id} ${local_registry_url}/${image} &>${LOGFILE}
-  docker push ${local_registry_url}/${image} &>${LOGFILE}
-  echo "Completed Push of image: ${image}"
-) &
-bg_pids="$bg_pids $!"
+  if $parallel; then
+    (
+      do_sync
+    ) &
+    bg_pids="$bg_pids $!"
+  else
+    do_sync
+  fi
 done
 
 count=1
