Added check for enabled repos

diff --git a/provisioning/openstack/create_base_image b/provisioning/openstack/create_base_image
--- a/provisioning/openstack/create_base_image
+++ b/provisioning/openstack/create_base_image
@@ -64,6 +64,16 @@ subscription-manager repos \
 --enable="rhel-7-server-extras-rpms" \
 --enable="rhel-7-server-optional-rpms" \
 --enable="rhel-7-server-ose-3.0-rpms"
+
+enabled_repos=`yum repolist`
+if [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-rpms\/\"`" ] || \
+   [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-extras-rpms\/\"`" ] || \
+   [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-optional-rpms\/\"`" ] || \
+   [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-ose-3.0-rpms\/\"`" ]; then
+  echo "Failed to enable required repos!"
+  exit 1
+fi
+
 yum clean all
 yum install -y wget git net-tools bind-utils iptables-services bridge-utils rsync
 yum update -y
