Updated tools to support OSEv3.1

diff --git a/provisioning/openstack/tailor_image_ose31 b/provisioning/openstack/tailor_image_ose31
--- a/provisioning/openstack/tailor_image_ose31
+++ b/provisioning/openstack/tailor_image_ose31
@@ -67,6 +67,23 @@ function _updateSyslog()
     postrotate/" /etc/logrotate.d/syslog
 }
 
+function _setRepos()
+{
+  subscription-manager repos --disable="*"
+  subscription-manager repos \
+  --enable="rhel-7-server-rpms" \
+  --enable="rhel-7-server-extras-rpms" \
+  --enable="rhel-7-server-ose-3.1-rpms"
+
+  enabled_repos=`yum repolist`
+  if [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-rpms\/\"`" ] || \
+     [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-extras-rpms\/\"`" ] || \
+     [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-ose-3.1-rpms\/\"`" ]; then
+    echo "Failed to enable required repos!"
+    exit 1
+  fi
+}
+
 function _updateRHSubscription()
 {
   # expects a file with RHN credentials of the format:
@@ -85,28 +102,17 @@ function _updateRHSubscription()
 
   subscription-manager register --username=${username} --password=${password}
   subscription-manager attach --pool=${poolid}
-  subscription-manager repos --disable="*"
-  subscription-manager repos \
-  --enable="rhel-7-server-rpms" \
-  --enable="rhel-7-server-extras-rpms" \
-  --enable="rhel-7-server-optional-rpms" \
-  --enable="rhel-7-server-ose-3.0-rpms"
-
-  enabled_repos=`yum repolist`
-  if [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-rpms\/\"`" ] || \
-     [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-extras-rpms\/\"`" ] || \
-     [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-optional-rpms\/\"`" ] || \
-     [ -z "`echo ${enabled_repos} | grep \" rhel-7-server-ose-3.0-rpms\/\"`" ]; then
-    echo "Failed to enable required repos!"
-    exit 1
-  fi
+  subscription-manager release --set=7.2
+  _setRepos
 }
 
 function _updateSoftware()
 {
   yum clean all
-  yum install -y wget git net-tools bind-utils iptables-services bridge-utils rsync lvm2
+  yum install -y wget git net-tools bind-utils iptables-services bridge-utils bash-completion rsync lvm2 
   yum update -y
+  yum install -y atomic-openshift-utils ansible
+  _setRepos
 }
 
 function _installCustomSoftware()
diff --git a/provisioning/osc-manage-image b/provisioning/osc-manage-image
--- a/provisioning/osc-manage-image
+++ b/provisioning/osc-manage-image
@@ -38,12 +38,26 @@ usage() {
   Options:
   --action=<action>             : Action to execute -- promote 
   --image-name                  : Name of the image to perform above action on
+  --ose-version                 : OSE version to use
   --debug                       : Will add -x to all bash commands
   "
 }
 
 
 do_promote() {
+  case $Version in
+    "3.0")
+      image_name="${image_name_30}"
+      ;;
+    "3.1")
+      image_name="${image_name_31}"
+      ;;
+    *)
+      echo "ERROR: Invalid OSE version specified - exiting..."
+      exit 1
+      ;;
+  esac
+
   prev_image_name="ose3-delete-after-`date --date="${image_retirement_lifespan}" +%d-%b-%Y`"
 
   echo -n "This will promote '${ImageName}' to '${image_name}' - do you want to continue? [Y]: "
@@ -100,6 +114,9 @@ do
       shift;;
     --image-name=*)
       ImageName="${i#*=}"
+      shift;;
+    --ose-version=*)
+      Version="${i#*=}"
       shift;;
     --debug)
       set -x;
