Modularized the install script into 'actions'. Also various enhancements and bug fixes to make install process go more smoothly

diff --git a/provisioning/osc-install b/provisioning/osc-install
--- a/provisioning/osc-install
+++ b/provisioning/osc-install
@@ -1,74 +1,186 @@
 #!/bin/bash
 
+## Functions
 
+# Show script usage
 usage() {
-  echo "Usage: $0 -m=|--master=\"<master hostname>\" -n=|--nodes=\"<node1 hostname>,..,<nodeN hostname>\""
+  echo "Usage: $0 -m=|--master=\"<master hostname>\" -n=|--nodes=\"<node1 hostname>,..,<nodeN hostname>\" -a|--actions=\"action1,action2,...actionN\""
 }
+
+contains () {
+  local e
+  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
+  return 1
+}
+
+process_actions() {
+  valid_actions='prep dns install post'
+  declare -a requested_actions=(${1//,/ })
+  declare -a final_actions
+
+  i=0
+  for action in ${valid_actions}; do
+    contains "$action" "${requested_actions[@]}"
+    [ "$?" == 0 ] && final_actions[$i]="$action" && requested_actions=( ${requested_actions[@]/$action/})
+    ((i++))
+  done
+
+  [ ! -z ${requested_actions} ] && echo "Unrecognized actions: ${requested_actions[@]}" && exit 1
+
+  for action in ${final_actions[@]}; do
+    do_$action
+  done
+}
+
+setup_ansible() {
+  for node in ${NODES//,/ }; do
+    nodestring="$nodestring
+    ${node} openshift_hostname=${node} openshift_public_hostname=${node}"
+  done
+
+  ansible_branch=${CONF_ANSIBLE_BRANCH:-"v3-beta3"}
+  ansible_hosts_file="# This is an example of a bring your own (byo) host inventory
+
+  [OSEv3:children]
+  masters
+  nodes
+
+  [OSEv3:vars]
+  deployment_type=enterprise
+  ansible_ssh_user=root
+  # Pre-release registry URL
+  #openshift_registry_url=docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-${component}:${version}
+  # Pre-release additional repo
+  #openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]
+
+  # host group for masters
+  [masters]
+  ${MASTER} openshift_hostname=${MASTER} openshift_public_hostname=${MASTER}
+
+  # host group for nodes
+  [nodes]
+  ${nodestring}
+  "
+
+  cd
+  rm -rf ~/openshift-ansible
+  git clone https://github.com/detiber/openshift-ansible.git -b $ansible_branch
+  cd ~/openshift-ansible
+  /bin/cp -r ~/training/beta3/ansible/* /etc/ansible/
+  cd
+
+  echo "$ansible_hosts_file" > /etc/ansible/hosts
+}
+
+setup_authentication() {
+  users=${CONF_OPENSHIFT_USERS:-"joe:redhat alice:redhat"}
+
+  # Set up authentication
+  yum -y install httpd-tools
+  touch /etc/openshift-passwd
+  for user in $users; do
+    htpasswd -b /etc/openshift-passwd ${user%:*} ${user#*:}
+  done
+
+  # edit master.yml oauth settings
+  sed -i -e 's/name: anypassword/name: apache_auth/' \
+  -e 's/kind: AllowAllPasswordIdentityProvider/kind: HTPasswdPasswordIdentityProvider/' \
+  -e '/kind: HTPasswdPasswordIdentityProvider/i \      file: \/etc\/openshift-passwd' \
+  /etc/openshift/master.yaml
+
+  systemctl restart openshift-master
+}
+
+setup_training_repo() {
+  cd
+  rm -rf ~/training
+  git clone https://github.com/openshift/training.git
+  cd
+}
+
+## Action functions
+do_prep() {
+  echo "Beginning action: Prep"
+  yum -y install http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
+  sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
+  sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/ose.repo
+  yum -y update
+  yum -y --enablerepo=epel install https://kojipkgs.fedoraproject.org//packages/ansible/1.8.4/1.el7/noarch/ansible-1.8.4-1.el7.noarch.rpm
+}
+
+do_dns() {
+  echo "Beginning action: DNS"
+  yum -y install bind
+
+  read -p "Copy named configs, then Press [Enter] key to continue... "
+  systemctl restart named
+
+  # iptables rules
+  udp='\-A INPUT \-p udp \-m state \-\-state NEW \-m udp \-\-dport 53 \-j ACCEPT'
+  tcp='\-A INPUT \-p tcp \-m state \-\-state NEW \-m tcp \-\-dport 53 \-j ACCEPT'
+  [ $(grep -c "$udp" /etc/sysconfig/iptables) == 0 ] && sed -i "/-A INPUT -j REJECT/i \
+  $udp" /etc/sysconfig/iptables
+  [ $(grep -c "$tcp" /etc/sysconfig/iptables) == 0 ] && sed -i "/-A INPUT -j REJECT/i \
+  $tcp" /etc/sysconfig/iptables
+
+  systemctl restart iptables
+
+  # configure resolv.conf
+  shopt -s extglob
+  resolv_conf="; generated by OpenShift provisioning script, $0
+search ${MASTER/+([a-z])./}
+nameserver $(ifconfig | grep -A 1 eth0 | awk '/inet/ {print $2}')"
+
+echo "$resolv_conf" > /etc/resolv.conf
+
+}
+
+do_install() {
+  if [ -z $MASTER ] || [ -z $NODES ]; then
+    echo "Missing required args"
+    usage
+    exit 1
+  fi
+
+  echo "Install"
+
+  setup_ansible
+  setup_training_repo
+
+  # Run ansible
+  ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
+}
+
+do_post(){
+  echo "Post Install"
+  setup_authentication
+}
+
 
 for i in "$@"
 do
   case $i in
     -m=*|--master=*)
-    MASTER="${i#*=}"
-    shift
-    ;;
+      MASTER="${i#*=}"
+      shift;;
     -n=*|--nodes=*)
-    NODES="${i#*=}"
-    shift
-    ;;
+      NODES="${i#*=}"
+      shift;;
+    -a=*|--actions=*)
+      ACTIONS="${i#*=}"
+      shift;;
     *)
-    echo "Invalid Option: ${i#*=}"
-    exit 1;
-    ;;
+      echo "Invalid Option: ${i#*=}"
+      exit 1;
+      ;;
   esac
 done
 
-if [ -z $MASTER ] || [ -z $NODES ]; then
+if [ -z $ACTIONS ]; then
   echo "Missing required args"
   usage
   exit 1
 fi
 
-ansible_branch="v3-beta3"
-ansible_hosts_file="# This is an example of a bring your own (byo) host inventory
-
-[OSEv3:children]
-masters
-nodes
-
-[OSEv3:vars]
-deployment_type=enterprise
-ansible_ssh_user=root
-# Pre-release registry URL
-#openshift_registry_url=docker-buildvm-rhose.usersys.redhat.com:5000/openshift3_beta/ose-${component}:${version}
-# Pre-release additional repo
-#openshift_additional_repos=[{'id': 'ose-devel', 'name': 'ose-devel', 'baseurl': 'http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0/$basearch/os', 'enabled': 1, 'gpgcheck': 0}]
-
-# host group for masters
-[masters]
-${MASTER}
-
-# host group for nodes
-[nodes]
-${NODES//,/$'\n'}
-"
-
-yum -y update
-yum -y install \
-http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
-sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo
-yum -y --enablerepo=epel install https://kojipkgs.fedoraproject.org//packages/ansible/1.8.4/1.el7/noarch/ansible-1.8.4-1.el7.noarch.rpm
-
-cd
-rm -rf ~/training
-git clone https://github.com/openshift/training.git
-rm -rf ~/openshift-ansible
-git clone https://github.com/detiber/openshift-ansible.git -b $ansible_branch
-cd ~/openshift-ansible
-/bin/cp -r ~/training/beta3/ansible/* /etc/ansible/
-cd
-
-echo "$ansible_hosts_file" > /etc/ansible/hosts
-
-# Run ansible
-ansible-playbook ~/openshift-ansible/playbooks/byo/config.yml
+process_actions ${ACTIONS?"Missing argument -a or --action"}
+exit 0;
